#### 1. tạo một mảng phần tử

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)


### 2. Tạo ra một mảng gồm n số 0. n nhập từ bàn phím

In [ ]:
# using numpy
new_arr = np.zeros(5)
print(new_arr)


# using list comprehension
new_arr_2 = [0] * 5
print(new_arr_2)

### 3. truy xuất và thay đổi phần tử trong danh sách

In [ ]:
# using list
l_data = [4, 5, 6, 7, 8, 9]

print(l_data[0]) # 4
print(l_data[-1]) # 9


# using numpy
num_data = np.array([1, 2, 3, 4, 5, 6])

print(num_data[0]) # 1
print(num_data[-1]) # 6

### 4. slicing trong danh sách

In [ ]:
# using l_data and num_data in previous cell.

print(l_data[1:4])  # [5, 6, 7]
print(l_data[:])    # lấy hết
print(l_data[:3])   # [4, 5, 6]
print(l_data[1::2]) # [5, 7, 9]
print(l_data[::2])  # [4, 6, 8]
print(l_data[4:])   # [8, 9]

print()

# same as list, numpy uses numpy array to slicing array.
print(num_data[1:4])  # [2 3 4]
print(num_data[:])    # lấy hết
print(num_data[:3])   # [1 2 3]
print(num_data[1::2]) # [2 4 6]
print(num_data[::2])  # [1 3 5]
print(num_data[4:])   # [5 6]

### 5. Thêm phần tử vào cuối danh sách


In [ ]:
# using data cell 3

# thêm 6 vào cuối list
l_data.append(6)

# thêm 7 vào cuối numpy.data
num_data = np.append(num_data, 7)

print(l_data)    # [4, 5, 6, 7, 8, 9, 6]
print(num_data)  # [1 2 3 4 5 6 7]


### 6. Thêm phần tử vào vị trí bất kỳ trong danh sách

In [ ]:
# using data cell 3

# thêm 2 vào index 1 trong list
l_data.insert(1, 2)
print(l_data)        # [4, 2, 5, 6, 7, 8, 9]

# thêm 5 vào index 3 trong list
num_data = np.insert(num_data, 2, 5)
print(num_data)      # [1 2 5 3 4 5 6]


### 7. Nối mảng trong danh sách

In [ ]:
# using data cell 3

# in list
# add [4, 5] to l_data
l_data.extend([4, 5])                  # [4, 5, 6, 7, 8, 9, 4, 5]
print(l_data)

# in numpy
# add [5 6] to num_data
num_data = np.append(num_data, [5, 6]) # [1 2 3 4 5 6 5 6]
print(num_data)

### 8. phép + và * trong danh sách

In [ ]:
# khai báo mảng list
list_data = [6, 5]
list_data_2 = [1, 9]

# khai báo mảng numpy
numpy_data = np.array([1, 2])
numpy_data_2 = np.array([3, 4])

# PHÉP CỘNG TRONG LIST VÀ NUMPY 
# phép cộng trong list giống như phép nối chuỗi
data_m = list_data_2 + list_data 
print(data_m)  # [6, 5, 1, 9]
#---------------------------------#


# phép cộng trong numpy là cộng các phần tử cùng chỉ số với nhau
numpy_m = numpy_data + numpy_data_2   
print(numpy_m) # [1+3, 2+4]
#---------------------------------#


# PHÉP NHÂN VỚI MỘT SỐ TỰ NHIÊN TRONG LIST VÀ NUMPY
# Trong list, phép nhân với một số là phép thêm vào cuối mảng n lần mảng đó.
# Xem ví dụ: ( chỉ nhân được với số tự nhiên )
multi_list = list_data * 3
print(multi_list)  # [6, 5, 6, 5, 6, 5]
#---------------------------------#

# trong numpy, phép nhân với một số là nhân từng phần tử của mảng với số đó. 
# thể hiện tính chất của ma trận ( nhân được với mọi số thực)
multi_num = numpy_data * (-3.5)
print(multi_num)   # [-3, -6]
#---------------------------------#

# trong numpy, phép nhân của numpy với nhau là kết quả của phép nhân từng phần tử 
# của numpy này cho numpy kia
multiple_numpy = numpy_data * numpy_data_2
print(multiple_numpy)  # [3 8]
#---------------------------------#

# trong list, phép nhân của list này với list kia không tồn tại.
multiple_list = list_data * list_data_2
print(multiple_list) # TYPE_ERROR


### 9. Sort trong danh sách

In [58]:
# khai báo mảng list
list_data = [6, 5, 4, 1, 2]
list_data_2 = [1, 9, 5, 6, 3]

# khai báo mảng numpy
numpy_data = np.array([1, 2, 4, 7, 2, 8])
numpy_data_2 = np.array([3, 5 ,4, 7, 8, 1, 2])

# Sort trong list: có thể sử dụng hàm built-in hoặc phương thức sort(Reverse = )
# hàm built-in phải gán.
list_data.sort(reverse = True)                              # [6, 5, 4, 2, 1]
list_data_2 = sorted(list_data_2, reverse = False)          # [1, 3, 5, 6, 9] 

print(list_data)
print(list_data_2)
#-----------------------------------------#

# sort trong numpy: có thể sử dụng numpy_built_in, phương thức np.sort() hoặc
# hàm built-in sorted()
# lưu ý:  muốn sort ngược chỉ có thể dùng [::-1] hoặc dùng sorted().
numpy_data.sort()                             # [1 2 2 4 7 8]
numpy_data = numpy_data[::-1]                 # [8 7 4 2 2 1]
numpy_data_2 = np.sort(numpy_data_2)          # [1 2 3 4 5 7 8]

print(numpy_data)
print(numpy_data_2)


[6, 5, 4, 2, 1]
[1, 3, 5, 6, 9]
[8 7 4 2 2 1]
[1 2 3 4 5 7 8]


### 10. Xóa phần tử trong danh sách

In [74]:
# trong list, muốn xóa phần tử theo index thì dùng pop(index), muốn xóa theo
# phần tử mình muốn thì dùng remove(element), lưu ý chỉ xóa được phần tử đầu tiên.

# trong numpy, ta chỉ có một phương thức duy nhất: np.delete(arr, remove_index_arr)
#       với:             
#                   arr                 : mảng có phần tử cần xóa
#                   remove_index_arr    : mảng những index chứa phần tử đó

# nếu muốn xóa tại vị trí nào đó, cần khai báo: np.delete(arr, remove_index) ( không cần mảng)
# nếu muốn xóa phần tử nào đó (ví dụ là 5), cần thực hiện hai bước:

# B1: removed_index_arr = np.where(arr = 5) ( nếu muốn xóa tại vị trí đầu tiên thì thêm [0][0])
# B2: np.delete(arr, remove_index_arr)


# ví dụ:

# tạo mảng bằng numpy:
an_arr = np.array([1,3,2,4,7,5,4,3])


# tuple các index có số 3.
remove_arr = np.where(an_arr == 3)

# delete first element 3
# remove_arr = np.where(an_arr == 3)[0][0]

# delete all numbers equal 3.
an_arr = np.delete(an_arr, remove_arr)
print(an_arr)   # [1 2 4 7 5 4]



[1 2 4 7 5 4]
[1 2 7 5]


### 11. xóa nhiều phần tử trong danh sách

In [79]:
# create data
a_data = np.array([1, 2, 3, 5, 6, 8, 9])

# delete element: 3 5 6
a_data = np.delete(a_data, np.arange(2,5))
print(a_data)
print()

# delete 2 8
a_data = np.concatenate((a_data[:1], a_data[3:]))
print(a_data)

[1 2 8 9]

[1 9]


### 12. Trả về vị trí index đầu tiên của số cần tìm. Đếm số lần xuất hiện.

In [87]:
# create data
a_data = np.array([1, 2, 3, 5, 2, 8, 9])


# find 2 (first index)
print(np.where(a_data == 2)[0])
print()


# đếm số lần xuất hiện của một số. lưu ý, khi ghi (a_data ==2), 
# một list có data type là bool sẽ được tạo, với những index của 
# 2 có giá trị là True, còn lại là false.
count_type = (a_data == 2)
count = (a_data == 2).sum()
print(count_type)
print(count)

[1 4]

[False  True False False  True False False]
2


#### ***high note: array can't contain any data type without number type.***

### 13. copy array and list

In [88]:
# same as list, numpy can use copy() function for copying any data from different numpy.

# create data
data = np.array([2,1,4,2,6,8,3,6])

new_copy = np.copy(data)
print(new_copy)  # copying

[2 1 4 2 6 8 3 6]


### 14. len, min and max in Numpy

In [94]:
# create data
data = np.array([1,5,3,6,3,6,7,7,8,3,5,2])

print(f'{np.min(data)}, {np.max(data)}, {len(data)}')   # 1, 8, 12


# warning : len() function not available in numpy, using built-in function.

# SOS
# demensional in numpy - array. - not a methods, not ().
print(data.shape)  # (12,)

1, 8, 12
(12,)


### 15. Sum and Zip in Numpy

In [111]:
# khai báo mảng numpy
numpy_data = np.array([1, 2, 3])
numpy_data_2 = np.array([3, 4, 5])

# sum methods in Numpy
print(np.sum(numpy_data))  # 6

# zip method in Numpy ( using dstack --> for stacking) 
# dstack nhận vào tuple, tách từng cặp trên-dưới rồi phát triển theo chiều dọc.
zipped_arr = np.dstack((numpy_data, numpy_data_2))[0]

for elements in range(len(zipped_arr)):
    print(zipped_arr[elements])

print(zipped_arr)


6
[[1 3]
 [2 4]
 [3 5]]
[[[1 3]
  [2 4]
  [3 5]]]


### 16. lấy cả index và giá trị trong cùng một lệnh

In [117]:
# implemented by @wanghii
# using np.ndenumerate. index is a tuple --> protection data.

a = np.array([1,2,3])

for index, value in np.ndenumerate(a):
    print(index, value)

(0,) 1
(1,) 2
(2,) 3


### 17. tính tổng các số chẵn + tổng các số tại index chẵn

In [124]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 9, 8])

# sum of even numbers

# create an array which contains nums even.
even_arr = arr[arr % 2 == 0]

# print preview 
print(even_arr)

# calculate sum of even_arr
print(np.sum(even_arr))
print()

# ----------------------------- #

# sum of values from even indices
even_idx_arr = arr[1::2]
print(even_idx_arr)
print(np.sum(even_idx_arr))




[2 4 6 8]
20

[2 4 6 9]
21


### 18. Advanced index. Boolean array.

In [128]:
# we can query many values at the same time with advanced index.
# ex:
a = np.array([1, 2, 3, 4, 5])

# [1, 3] is a list of indices need to access.
print(a[[1, 3]])                # print 2 and 4 in an array.


# using Boolean in Numpy to access.
print(a[a > 3])


[2 4]
[4 5]


### 19. More advanced indices

In [138]:
# create an array
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([2, 3, 4, 5])
arr3 = np.array([[1, 2],
                [3, 4]])
arr4 = np.array([[1, 2, 3],
                [2, 3, 4]])

# nối 2 array --> khi sử dụng concatenate phải đưa hai biến vào tuple trước khi gọi hàm
arr_result = np.concatenate((arr1 , arr2))


#  chuyển từ ma trận nhiều chiều thành một chiều --> hàm này chỉ dành cho đối tượng, không phải
# phương thức của np
arr_1D = arr3.flatten()  


# reshape lại ma trận - chỉ dành cho đối tượng, reshape theo hàng - cột
arr_reshape = arr4.reshape(3, 2)


print(arr_result)
print(arr_1D)
print(arr_reshape)

[1 2 3 4 2 3 4 5]
[1 2 3 4]
[[1 2]
 [3 2]
 [3 4]]


### 20. Broadcasting in Numpy - important

In [144]:
# cộng - nhân hai vector không cùng chiều (mismatch shape) 
a = np.array([[1, 2], [3, 4], [5, 6]])  # matrix 3x2
b = np.array([1, 2])                    # matrix 2x1


# cơ chế thực thi: mở rộng array kích thước nhỏ để phù hợp cho vector kích thước lớn
# trong trường hợp này, ta mở rộng vector b --> ([1, 2], [1, 2], [1, 2]) rồi cộng
# tương ứng từng vị trí (elements-wise) cho vector a. Lưu ý: số cột phải giống nhau.

c = a + b   # a+b mở rộng 3 hàng 
d = a*b     # a*b mở rộng 3 hàng
print(c, d, sep='\n')
 

[[2 4]
 [4 6]
 [6 8]]
[[ 1  4]
 [ 3  8]
 [ 5 12]]


### 21. Vectorization in Numpy - faster than list

In [151]:
# by vectorization, we don't have to use loop.
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# vectorization
p = a*b


# in list
c = [1, 2, 3, 4]
d = [5, 6, 7, 8]


# for + list comprehension
result = [x*y for x, y in zip(a, b)]


print(p)
print(result)

[ 5 12 21 32]
[5, 12, 21, 32]
